name: Package and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies (notifications)
        run: |
          cd notifications
          npm ci
      - name: Install dependencies (customer-app)
        run: |
          cd ../customer-app
          npm ci

      - name: Run tests with coverage
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack notifications_lupaca
        run: |
          cd notifications
          npm version patch
          npm pack

      - name: Pack customer-app_lupaca
        run: |
          cd ../customer-app
          npm version patch
          npm pack

      - name: Publish notifications_lupaca to GitHub Packages
        run: |
          cd ../notifications
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish customer-app_lupaca to GitHub Packages
        run: |
          cd ../customer-app
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
